### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by rebaz36** [rebaz36/M1Capstone#5]
Hey, guys check out my code for Module 1 Capstone project. feel free to leave any comments feedbacks and suggestions

**Comment by diegoh40** [comment]
kindly, I recommend you use the CSS alphabetical order to control your variables better when making any changes.

**Comment by Apatakiti** [comment]
## Hi Rebaz

You have dona a great job so far
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

I suggest that the size of the webpage increase and decrease in font and layout as the screen also increase and decrease for individuals with smaller screen be able to view the hidden parts.
